name: Deploy to FTP Dar ichkeul Project

on:
  push:
    branches:
      - main

  # the follow line allow this script to be started manually.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages with NPM
      run: npm install --force
    - name: Build for production
      run: npm run build 
    - name: Upload artifacts to be used in next job
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: deploy_dist
        path: dist

  ftp-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Download artifacts created at previous job
      if: success()
      uses: actions/download-artifact@v1
      with:
        name: deploy_dist
        path: dist
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.cluster030.hosting.ovh.net
        username: darichr
        password: 5S5e171078
        local-dir: dist/hotels/
        server-dir: "www/TEST_DARICHKEUL/Miranda/"
        dangerous-clean-slate: true # optional
